sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

env:
  - DOCKERFILE=Dockerfile DOCKERNAME=""
  - DOCKERFILE=share/vizd/docker/Dockerfile-test DOCKERNAME="-test"
  - DOCKERFILE=share/vizd/docker/Dockerfile-testnet DOCKERNAME="-testnet"
  - DOCKERFILE=share/vizd/docker/Dockerfile-lowmem DOCKERNAME="-lowmem"
  - DOCKERFILE=share/vizd/docker/Dockerfile-mongo DOCKERNAME="-mongo"

matrix:
  fast_finish: true

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export DOCKERNAME="latest""$DOCKERNAME";
      export EXPORTNAME="$DOCKERNAME";
    elif [ -n "$TRAVIS_TAG" ]; then
      export DOCKERNAME="$TRAVIS_TAG""$DOCKERNAME";
      export EXPORTNAME="$DOCKERNAME";
    else
      export DOCKERNAME=develop"$DOCKERNAME";
    fi
  - echo "$DOCKERFILE"
  - echo "$DOCKERNAME"
  - docker build -t viz-world/viz-world:"$DOCKERNAME" -f "$DOCKERFILE" .

after_success:
  - echo "$EXPORTNAME"
  - docker images
  - if [ -n "$EXPORTNAME" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push viz-world/viz-world:"$EXPORTNAME";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" -a "$EXPORTNAME" == "latest" ]; then
      bash deploy/deploy.sh;
    fi
