name: Build testnet docker image for a PR

on: [pull_request]

jobs:
  build_image:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vizblockchain/vizd
          dockerfile: ./share/vizd/docker/Dockerfile-testnet
          tag_with_ref: true
